"""Copy the Plasma Wave Workbench from ~/self-study into /projects/.

The workbench is developed in the (private) self-study repo. Its
`tools/build.py --standalone` writes one self-contained HTML file; this
script copies that file here and adds what a page on this site needs:

  - a small "back to projects" bar,
  - a favicon and a web-app manifest, so it can be added to the home screen,
  - a service worker, so after one visit it keeps working offline (on the train).

Re-run it whenever the workbench changes:

    cd ~/self-study/basic && python3 tools/build.py --standalone
    cd ~/iceqbie.github.io && python3 tools/import-workbench.py
"""

import hashlib
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SOURCE = pathlib.Path(
    sys.argv[1] if len(sys.argv) > 1
    else "~/self-study/basic/workbench/dist/workbench-standalone.html"
).expanduser()
OUT = REPO / "projects" / "plasma-wave-workbench"

HEAD = """<meta name="description" content="Plasma Wave Workbench: scales, assumptions, the CMA diagram, a 3D particle viewer and unit conversion over one shared plasma.">
<meta name="theme-color" content="#1F6F86">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/assets/icons/icon-180.png">
<link rel="manifest" href="manifest.webmanifest">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Workbench">
"""

BAR = """<nav aria-label="Site" style="display:flex;justify-content:space-between;align-items:center;gap:12px;padding:10px 16px;font:13px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;border-bottom:1px solid rgba(0,0,0,.08)">
<a href="/projects/" style="color:#1F6F86;text-decoration:none;min-height:32px;display:inline-flex;align-items:center">← icebox. / projects</a>
<span id="offline-status" style="color:#667483"></span>
</nav>
"""

REGISTER = """<script>
/* Offline support: cache this page so it opens without signal. */
if ("serviceWorker" in navigator) {
  const status = document.getElementById("offline-status");
  navigator.serviceWorker.register("sw.js").then(() => navigator.serviceWorker.ready).then(() => {
    if (status) status.textContent = "✓ available offline";
  }).catch(() => {});
}
</script>
"""

SW = """/* Service worker for the Plasma Wave Workbench (generated by tools/import-workbench.py).
   Pages: try the network for a fresh copy, but fall back to the cache after
   3 s so a weak train signal doesn't leave you waiting. Fonts and icons:
   cache first. */

const VERSION = "__VERSION__";
const CACHE = `workbench-${VERSION}`;
const PRECACHE = ["./", "manifest.webmanifest", "/favicon.svg", "/assets/icons/icon-180.png", "/assets/icons/icon-512.png"];

self.addEventListener("install", (event) => {
    event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
    event.waitUntil(
        caches.keys()
            .then((keys) => Promise.all(keys.filter((k) => k.startsWith("workbench-") && k !== CACHE).map((k) => caches.delete(k))))
            .then(() => self.clients.claim())
    );
});

function networkFirst(request) {
    return caches.open(CACHE).then((cache) => {
        const network = fetch(request).then((response) => {
            if (response.ok) cache.put(request, response.clone());
            return response;
        });
        const timeout = new Promise((resolve) => setTimeout(resolve, 3000));
        return Promise.race([network, timeout.then(() => cache.match(request))])
            .then((response) => response || network)
            .catch(() => cache.match(request).then((cached) => cached || cache.match("./")));
    });
}

function cacheFirst(request) {
    return caches.open(CACHE).then((cache) =>
        cache.match(request).then((cached) => cached || fetch(request).then((response) => {
            if (response.ok || response.type === "opaque") cache.put(request, response.clone());
            return response;
        }))
    );
}

self.addEventListener("fetch", (event) => {
    const url = new URL(event.request.url);
    if (event.request.method !== "GET") return;

    if (event.request.mode === "navigate" && url.pathname.startsWith("/projects/plasma-wave-workbench/")) {
        event.respondWith(networkFirst(event.request));
    } else if (/fonts\\.(googleapis|gstatic)\\.com$/.test(url.hostname) || url.origin === location.origin) {
        event.respondWith(cacheFirst(event.request));
    }
});
"""

MANIFEST = {
    "name": "Plasma Wave Workbench",
    "short_name": "Workbench",
    "description": "Plasma scales, assumptions, CMA diagram, 3D viewer and units — works offline.",
    "start_url": "./",
    "scope": "./",
    "display": "standalone",
    "background_color": "#fafaf8",
    "theme_color": "#1F6F86",
    "icons": [
        {"src": "/assets/icons/icon-180.png", "sizes": "180x180", "type": "image/png"},
        {"src": "/assets/icons/icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any maskable"},
    ],
}


def insert_once(html, marker, text, after=True):
    if html.count(marker) < 1:
        sys.exit(f"import-workbench: marker {marker!r} not found in {SOURCE}")
    i = html.index(marker) if not after else html.index(marker) + len(marker)
    if marker == "</body>":
        i = html.rindex(marker)
    return html[:i] + text + html[i:]


def main():
    html = SOURCE.read_text(encoding="utf8")

    html = insert_once(html, "</head>", HEAD, after=False)
    html = insert_once(html, "<body>\n", BAR)
    html = insert_once(html, "</body>", REGISTER, after=False)

    version = hashlib.sha256(html.encode("utf8")).hexdigest()[:12]

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "index.html").write_text(html, encoding="utf8")
    (OUT / "sw.js").write_text(SW.replace("__VERSION__", version), encoding="utf8")
    (OUT / "manifest.webmanifest").write_text(json.dumps(MANIFEST, indent=4, ensure_ascii=False) + "\n", encoding="utf8")

    kb = len(html.encode("utf8")) / 1024
    print(f"  wrote {OUT.relative_to(REPO)}/index.html ({kb:.0f} KB), sw.js (cache {version}), manifest.webmanifest")


if __name__ == "__main__":
    main()
